display_name: OPC Node designer
package_name: opcnodedesigner

maintainer:
  name: Andrei Lacatos
  email: lacatos_andrei@yahoo.com

priority: optional

section: x11

essential: false
installed_size: 23720
generic_name: OPC Node designer

categories:
  - Development
  - Utility
